{{ $url := include "kib-es-url" . }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "influx-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "influx-fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ template "influx-fullname" . }}
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: {{ template "influx-fullname" . }}
    spec:
      containers:
      - name: influx 
        image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
{{ toYaml .Values.environment_variables | indent 10 }}
        command:
          - kibana #changeme!!!!!!!!
        ports:
        {{- $root := . -}}
        {{- range .Values.Services.Elasticsearch.Nodes }}
         - containerPort: {{ .targetPort }}
           name: "port_{{ default default .targerPort}}_{{ default TCP .protocol | upper }}"
        {{- end}}
        volumeMounts:
          - name: config
            mountPath: /etc/influxdb
      volumes:
      - name: config
        configMap:
          name: {{ template "influx-cm-fullname" . }}
          items:
            - key: influx-conf
              path: influxdb.conf
