apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fluent-cm-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fluent-fullname" . }}
data:
  fluent-conf: |
    <source>
      @type  forward
      @id    input1
      @label @mainstream
      pmort  24224
    </source>

    <filter **>
      @type stdout
    </filter>

    <label @mainstream>
      <match docker.**>
        @type file
        @id   output_docker1
        path         /fluentd/log/docker.*.log
        symlink_path /fluentd/log/docker.log
        append       true
        time_slice_format %Y%m%d
        time_slice_wait   1m
        time_format       %Y%m%dT%H%M%S%z
      </match>
      <match **>
        @type file
        @id   output1
        path         /fluentd/log/data.*.log
        symlink_path /fluentd/log/data.log
        append       true
        time_slice_format %Y%m%d
        time_slice_wait   10m
        time_format       %Y%m%dT%H%M%S%z
      </match>
    </label>
  {{- if .Values.service.configurations }}
  {{- range .Values.confiurations }}
  "{{ .name}}:" |
{{ toYaml .content | indent 4 }}   
  {{- end}}
  {{- end -}}
