{{ $url := include "elasticsearch-url" . }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fluent-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fluent-fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ template "fluent-fullname" . }}
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: {{ template "fluent-fullname" . }}
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
              "name": "wait-for-es",
              "image": "{{ .Values.testImage.repository }}{{ .Values.testImage.name }}:{{ .Values.testImage.tag }}",
              "imagePullPolicy": {{ .Values.testImage.pullPolicy | quote }},
              "command": ["sh", "-c", "until [ $(curl -o /dev/null --silent -f {{ $url }}/; echo $?) -eq 0 ]; do sleep 10; done"]
          }
        ]'
    spec:
      containers:
      - name: fluentd
        image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        command:
          - kibana ##change me!!!!!!!!!!!!!
        env:
{{ toYaml .Values.environment_variables | indent 10 }}
        ports:
        {{- range .Values.ports }}
         - containerPort: {{ .targetPort }}
           name: "port_{{ default default .targerPort}}_{{ default TCP .protocol | upper }}"
        {{- end}}
        volumeMounts:
          - name: default-config
            mountPath: /fluentd/etc
      volumes:
      - name: default-config
        configMap:
          name: {{ template "fluent-cm-fullname" . }}
          items:
            - key: fluentd-conf
              path: fluentd.conf
            {{- if .Values.service.configurations }}
            {{- range .Values.confiurations }}
            - key: {{ .name }}
              path: "{{ .name }}.conf"
            {{- end}}
            {{- end -}} 
