apiVersion: v1
kind: Service
metadata:
  name: {{ template "fluent-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fluent-fullname" . }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4}}
{{- end }}
spec:
  type: {{ .Values.service.type | quote }}
  selector:
    app: {{ template "fluent-fullname" . }}
  ports:
    {{- $root := . -}}
    {{- range .Values.ports }}
    - name: "port_{{ default default .targerPort}}_{{ default TCP .protocol | upper }}"
      port: {{ default 8087 .targetPort }}
      targetPort: {{ .targetPort }}
      protocol: {{ default TCP .protocol | upper }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end}}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.data.service.loadBalancerSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end -}}
  {{- end -}}
