{{- $root := . -}}
{{- range .Values.Services.Elasticsearch.Nodes }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ $root.Values.Services.Elasticsearch.Name }}-{{.}}"
  labels:
    heritage: {{$root.Release.Service | quote }}
    release: {{$root.Release.Name | quote }}
    chart: "{{$root.Chart.Name}}-{{$root.Chart.Version}}"
    component: "{{$root.Release.Name}}-{{$root.Values.Services.Elasticsearch.Component}}-{{.}}"
    run: "{{ $root.Values.Services.Elasticsearch.Name }}-{{.}}"
spec:
  type: {{ $root.Values.Services.Elasticsearch.ServiceType | default "ClusterIP" }}
  ports:
  - name: "{{ $root.Values.Services.Elasticsearch.Name }}-{{.}}" 
    protocol: TCP
    port: {{$root.Values.Services.Elasticsearch.ExposedPort | default 9200}}
    targetPort: {{$root.Values.Services.Elasticsearch.ContainerPort | default 9200}}
  selector:
    run: "{{ $root.Values.Services.Elasticsearch.Name }}-{{.}}"
---
{{- end}}
