{{ $url := include "elasticsearch-url" . }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "curator-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "curator-fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ template "curator-fullname" . }}
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: {{ template "curator-fullname" . }}
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
              "name": "wait-for-es",
              "image": "{{ .Values.testImage.repository }}{{ .Values.testImage.name }}:{{ .Values.testImage.tag }}",
              "imagePullPolicy": {{ .Values.testImage.pullPolicy | quote }},
              "command": ["sh", "-c", "until [ $(curl -o /dev/null --silent -f {{ $url }}/; echo $?) -eq 0 ]; do sleep 10; done"]
          }
        ]'
    spec:
      containers:
      - name: curator
        image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
{{ toYaml .Values.environment_variables | indent 10 }}
        command:
          - kibana #changemeee!!!
        volumeMounts:
          - name: config
            mountPath: /
      volumes:
      - name: config
        configMap:
          name: {{ template "curator-cm-fullname" . }}
          items:
            - key: conf
              path: config.yml
            - key: action
              path: action.yml
